# frozen_string_literal: true

require "test_helper"
require "action_dispatch"
require "fileutils"
require "yaml"

class InitGeneratorTest < Rails::Generators::TestCase
  tests RailsApiDocs::Generators::InitGenerator
  destination File.expand_path("../tmp", __dir__)
  setup :prepare_destination

  def setup
    super
    @routes = ActionDispatch::Routing::RouteSet.new
    @routes.draw do
      resources :users
      resources :posts, only: [:index, :create]
    end
    RailsApiDocs.configuration.route_source = @routes
  end

  def teardown
    super
    RailsApiDocs.reset_configuration!
  end

  def test_creates_yaml_at_default_path
    run_generator
    assert_file "config/rails-api-docs.yml"
  end

  def test_yaml_starts_with_header_comment
    run_generator
    assert_file "config/rails-api-docs.yml" do |content|
      assert_match(/\A# config\/rails-api-docs\.yml/, content)
      assert_match(/Auto-generated by rails-api-docs/, content)
    end
  end

  def test_yaml_contains_general_configurations_and_sections
    run_generator
    assert_file "config/rails-api-docs.yml" do |content|
      assert_match(/general_configurations:/, content)
      assert_match(/primary_color:\s*"?#CC0000"?/, content)
      assert_match(/sections:/, content)
      assert_match(/^\s+users:/, content)
      assert_match(/^\s+posts:/, content)
    end
  end

  def test_yaml_is_parseable_after_header
    run_generator
    raw      = File.read(File.join(destination_root, "config/rails-api-docs.yml"))
    parsed   = YAML.safe_load(raw)

    assert_kind_of Hash, parsed
    assert_equal "#CC0000", parsed.dig("general_configurations", "primary_color")
    assert parsed["sections"]["users"]
    assert_equal "Users", parsed["sections"]["users"]["name"]
  end

  def test_first_run_creates_then_second_run_is_a_no_op_when_routes_unchanged
    run_generator
    before = File.read(File.join(destination_root, "config/rails-api-docs.yml"))

    output = run_generator
    after  = File.read(File.join(destination_root, "config/rails-api-docs.yml"))

    assert_equal before, after, "file content should be identical when no routes changed"
    assert_match(/unchanged/, output)
  end

  def test_second_run_appends_only_new_routes_and_preserves_edits
    run_generator
    path = File.join(destination_root, "config/rails-api-docs.yml")

    # Simulate user edits: add a description to one endpoint and a comment to the header.
    config = YAML.safe_load(File.read(path))
    user_endpoint = config["sections"]["users"]["endpoints"].find { |e| e["method"] == "POST" }
    user_endpoint["description"] = "Custom user-written description"
    user_endpoint["body"] = [{ "name" => "name", "type" => "string", "required" => true }]
    header_with_note = "# my project notes\n" + File.read(path).lines.drop_while { |l| l.start_with?("#") || l.strip.empty? }.join
    File.write(path, header_with_note.lines.take_while { |l| l.start_with?("#") || l.strip.empty? }.join + YAML.dump(config))

    # Now add a new route and re-run
    @routes.draw do
      resources :comments, only: [:index, :create]
    end

    output = run_generator

    reloaded = YAML.safe_load(File.read(path))

    # User edits survived
    preserved = reloaded["sections"]["users"]["endpoints"].find { |e| e["method"] == "POST" }
    assert_equal "Custom user-written description", preserved["description"]
    assert_equal "name", preserved.dig("body", 0, "name")

    # User header note survived
    assert_match(/# my project notes/, File.read(path))

    # New section was appended
    assert reloaded["sections"]["comments"]
    assert_match(/updated/, output)
    assert_match(/\+1 section/, output)
  end

  def test_second_run_appends_new_endpoint_into_existing_section
    run_generator
    path = File.join(destination_root, "config/rails-api-docs.yml")

    # Add a custom action to the users controller
    @routes.draw do
      get "/users/me", to: "users#me"
    end

    run_generator

    reloaded = YAML.safe_load(File.read(path))
    paths    = reloaded["sections"]["users"]["endpoints"].map { |e| [e["method"], e["path"]] }

    assert_includes paths, ["GET", "/users/me"]
  end

  # ---------------- --api-only flag ----------------

  # Drop a few controllers in the destination so JsonRouteDetector finds them.
  def seed_mixed_controllers
    base = File.join(destination_root, "app/controllers")
    FileUtils.mkdir_p(base)

    File.write(File.join(base, "application_controller.rb"), <<~RUBY)
      class ApplicationController < ActionController::Base
      end
    RUBY
    File.write(File.join(base, "users_controller.rb"), <<~RUBY)
      class UsersController < ActionController::API
        def index; end
        def show; end
        def create; end
        def update; end
        def destroy; end
      end
    RUBY
    File.write(File.join(base, "posts_controller.rb"), <<~RUBY)
      class PostsController < ApplicationController
        def index; render :index; end
        def create; render :index; end
      end
    RUBY
  end

  def test_api_only_flag_filters_html_controllers
    seed_mixed_controllers
    run_generator ["--api-only"]

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))

    # users (API-only controller) survives; posts (HTML, no render json) is filtered out.
    assert yaml["sections"]["users"], "expected users section to remain"
    refute yaml["sections"]["posts"], "expected posts section to be filtered out"
  end

  def test_api_only_flag_keeps_html_action_with_render_json
    seed_mixed_controllers
    File.write(File.join(destination_root, "app/controllers/posts_controller.rb"), <<~RUBY)
      class PostsController < ApplicationController
        def index; render :index; end
        def create; render json: @post; end
      end
    RUBY

    run_generator ["--api-only"]

    yaml  = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    posts = yaml["sections"]["posts"]["endpoints"].map { |e| [e["method"], e["path"], e["name"]] }

    # create kept (has render json), index dropped (no render json).
    assert(posts.any? { |m, p, _| m == "POST" && p == "/posts" }, "expected POST /posts to remain")
    refute(posts.any? { |m, p, _| m == "GET"  && p == "/posts" }, "expected GET /posts to be filtered")
  end

  def test_api_only_falls_back_to_global_config_when_flag_omitted
    seed_mixed_controllers
    RailsApiDocs.configuration.api_only = true

    run_generator   # no flag

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    assert yaml["sections"]["users"]
    refute yaml["sections"]["posts"]
  end

  def test_no_api_only_flag_overrides_global_config
    seed_mixed_controllers
    RailsApiDocs.configuration.api_only = true

    run_generator ["--no-api-only"]

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    # Flag wins over config — posts comes back.
    assert yaml["sections"]["users"]
    assert yaml["sections"]["posts"]
  end

  def test_api_only_without_filter_keeps_all_routes
    seed_mixed_controllers
    # No flag, no config — default behavior unchanged.
    run_generator

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    assert yaml["sections"]["users"]
    assert yaml["sections"]["posts"]
  end

  # ---------------- --only-controllers flag ----------------

  def seed_three_resources
    @routes = ActionDispatch::Routing::RouteSet.new
    @routes.draw do
      resources :users,    only: [:index, :show]
      resources :posts,    only: [:index, :show]
      resources :comments, only: [:index]
    end
    RailsApiDocs.configuration.route_source = @routes
  end

  def yaml_keys
    YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))["sections"].keys.sort
  end

  def test_only_controllers_with_space_separated_form
    seed_three_resources
    run_generator ["--only-controllers", "users", "posts"]

    assert_equal %w[posts users], yaml_keys
  end

  def test_only_controllers_with_comma_separated_form
    seed_three_resources
    run_generator ["--only-controllers=users,posts"]

    assert_equal %w[posts users], yaml_keys
  end

  def test_only_controllers_with_bracket_form
    seed_three_resources
    run_generator ["--only-controllers=[users,posts]"]

    assert_equal %w[posts users], yaml_keys
  end

  def test_only_controllers_with_bracket_form_and_whitespace_inside
    seed_three_resources
    run_generator ["--only-controllers=[ users , posts ]"]

    assert_equal %w[posts users], yaml_keys
  end

  def test_only_controllers_combined_with_api_only_intersects_filters
    # Build a fresh RouteSet inline so we control the route order/count
    # precisely (avoids double-draw quirks on the setup-shared @routes).
    routes = ActionDispatch::Routing::RouteSet.new
    routes.draw do
      resources :users
      resources :posts,    only: [:index, :create]
      resources :comments, only: [:index]
    end
    RailsApiDocs.configuration.route_source = routes

    seed_mixed_controllers
    File.write(File.join(destination_root, "app/controllers/posts_controller.rb"), <<~RUBY)
      class PostsController < ApplicationController
        def index; render :index; end
        def create; render json: @post; end
      end
    RUBY
    File.write(File.join(destination_root, "app/controllers/comments_controller.rb"), <<~RUBY)
      class CommentsController < ApplicationController
        def index; render :index; end
      end
    RUBY

    # Whitelist: users + comments. Plus --api-only.
    # Expected: users (API-only) ∈ both filters → in.
    # comments (HTML, no json) ∈ whitelist but blocked by --api-only → out.
    # posts not in whitelist → out (regardless of --api-only).
    run_generator ["--only-controllers", "users", "comments", "--api-only"]

    keys = yaml_keys
    assert_includes keys, "users"
    refute_includes keys, "comments"
    refute_includes keys, "posts"
  end

  def test_only_controllers_falls_back_to_global_config
    seed_three_resources
    RailsApiDocs.configuration.only_controllers = ["users"]

    run_generator   # no flag

    assert_equal %w[users], yaml_keys
  end

  def test_only_controllers_flag_overrides_global_config
    seed_three_resources
    RailsApiDocs.configuration.only_controllers = ["users"]

    run_generator ["--only-controllers", "posts"]

    assert_equal %w[posts], yaml_keys
  end

  def test_only_controllers_with_namespaced_exact_path
    @routes = ActionDispatch::Routing::RouteSet.new
    @routes.draw do
      resources :users, only: [:index]
      namespace :api do
        namespace :v1 do
          resources :users, only: [:index]
        end
      end
    end
    RailsApiDocs.configuration.route_source = @routes

    run_generator ["--only-controllers", "api/v1/users"]

    assert_equal ["api/v1/users"], yaml_keys
  end

  def test_only_controllers_with_bare_name_matches_across_namespaces
    @routes = ActionDispatch::Routing::RouteSet.new
    @routes.draw do
      resources :users, only: [:index]
      namespace :api do
        namespace :v1 do
          resources :users, only: [:index]
        end
      end
    end
    RailsApiDocs.configuration.route_source = @routes

    run_generator ["--only-controllers", "users"]

    assert_equal ["api/v1/users", "users"], yaml_keys
  end

  # ---------------- --verbose-yaml flag ----------------

  def test_verbose_yaml_flag_emits_all_endpoint_keys
    run_generator ["--verbose-yaml"]

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    endpoint = yaml["sections"]["users"]["endpoints"].first

    assert_equal false, endpoint["deprecated"]
    assert_equal "",    endpoint["auth"]
    assert_equal [],    endpoint["tags"]
    assert_equal "",    endpoint["request_example"]
    stub = endpoint["responses"]["200"]
    assert_equal [],    stub["headers"]
    assert_equal [],    stub["schema"]
  end

  def test_verbose_yaml_falls_back_to_global_config
    RailsApiDocs.configuration.verbose_yaml = true
    run_generator

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    assert yaml["sections"]["users"]["endpoints"].first.key?("deprecated")
  end

  def test_pragmatic_mode_default_omits_verbose_keys
    run_generator   # no flag, no config

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    endpoint = yaml["sections"]["users"]["endpoints"].first
    %w[deprecated auth tags request_example].each do |k|
      refute endpoint.key?(k), "expected #{k} not emitted by default"
    end
  end

  def test_pragmatic_mode_still_emits_description_and_example_on_params
    run_generator

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))
    show = yaml["sections"]["users"]["endpoints"].find { |e| e["method"] == "GET" && e["path"] == "/users/:id" }
    id   = show["params"].first

    assert_equal "", id["description"]
    assert_equal 1,  id["example"]
  end

  def test_verbose_yaml_and_api_only_compose
    # Two flags operate on different pipeline stages — filtering (api-only)
    # runs before construction (verbose-yaml), so they should compose cleanly.
    seed_mixed_controllers   # users is API, posts is HTML

    routes = ActionDispatch::Routing::RouteSet.new
    routes.draw do
      resources :users, only: [:create]
      resources :posts, only: [:create]
    end
    RailsApiDocs.configuration.route_source = routes

    run_generator ["--api-only", "--verbose-yaml"]

    yaml = YAML.safe_load(File.read(File.join(destination_root, "config/rails-api-docs.yml")))

    # api-only filtered out posts (HTML controller, no render json)
    assert_equal ["users"], yaml["sections"].keys

    # verbose-yaml emitted all advanced endpoint keys on the surviving route
    endpoint = yaml["sections"]["users"]["endpoints"].first
    %w[deprecated auth tags headers request_example].each do |k|
      assert endpoint.key?(k), "expected verbose key #{k} on the api-only-filtered endpoint"
    end
    stub = endpoint["responses"]["200"]
    assert_equal [], stub["headers"]
    assert_equal [], stub["schema"]
  end
end
